apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-contour-envoy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: users        # your backend app pods
  policyTypes:
  - Ingress
  ingress:
  - from:
      - namespaceSelector:
          matchLabels:
            app: projectcontour      # label your contour namespace accordingly
        podSelector:
          matchLabels:
            app: envoy               # traffic must come from envoy pods
    ports:
      - protocol: TCP
        port: 8080                   # your app port
